### ISSUE TITLE
Repository directory structure

### ISSUE THREAD

**Issue by gothub** [DataONEorg/api-entrypoint#3]
@csjx Possible contents of this repo are:
- files needed to deploy the k8s NGINX Ingress Controller and Virtual Server resources
- files needed to deploy a HAProxy or other load balancer / reverse proxy

Here is a proposed directory layout for the repo:
```
- deployments
  - haproxy?
  - nginx-ingress-controller
      - virtual-server
        - helm-chart
        - manifests
          - common
          - deployment
          - rbac
          - service
- docs
```
How does this look to you?
Is there anything else that might be in this repo?

**Comment by csjx** [comment]
Heya @gothub - Yup, that looks good. We can adjust as needed, but it seems like everything of significance will be a deployment, and if we use something other than `haproxy` we can adjust. Thanks!

**Comment by gothub** [comment]
k8s control plane, networking, RBAC, etc is described in the [k8s-cluster](https://github.com/DataONEorg/k8s-cluster) repo.

Individual k8s app deployments are maintained in their own repos:
- https://github.com/DataONEorg/slinky
- https://github.com/NCEAS/metadig-engine
- https://github.com/DataONEorg/gnis-ld.org
